services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python p/manage.py collectstatic --noinput
    startCommand: gunicorn p.wsgi:application
